spring:
  application:
    name: servico-agendamento
  datasource:
    url: ${AGENDAMENTO_DB_URL:jdbc:postgresql://localhost:5432/hospital?currentSchema=agendamento}
    username: ${POSTGRES_USER:hospital_app}
    password: ${POSTGRES_PASSWORD:123456}
  flyway:
    default-schema: agendamento
    schemas: agendamento
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
