apply plugin: 'org.springframework.boot'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'org.postgresql:postgresql'

    implementation project(':contratos-grpc')
    implementation 'io.grpc:grpc-netty-shaded:1.83.1'
    implementation 'io.grpc:grpc-protobuf:1.83.1'
    implementation 'io.grpc:grpc-stub:1.83.1'
    implementation("net.devh:grpc-server-spring-boot-starter:3.1.0.RELEASE")

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('bootJar') {
    archiveFileName = 'app.jar'
}
