apply plugin: 'org.springframework.boot'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation project(':contratos-grpc')
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation("net.devh:grpc-client-spring-boot-starter:3.1.0.RELEASE")
    implementation 'io.grpc:grpc-netty-shaded:1.83.1'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
}

tasks.named('bootJar') {
    archiveFileName = 'app.jar'
}
